"use client";

import { forwardRef } from "react";
import { ReportRecord } from "./reports-history-table";

interface PrintableReportProps {
  reportData: ReportRecord | null;
}

// forwardRef is required so the print engine can target this exact component
export const PrintableReport = forwardRef<HTMLDivElement, PrintableReportProps>(
  ({ reportData }, ref) => {
    if (!reportData) return null;

    return (
      <div className="hidden">
        {/* The actual printable area. The [-webkit-print-color-adjust:exact] forces the black headers to print */}
        <div ref={ref} className="print:block print:p-10 font-sans text-black [-webkit-print-color-adjust:exact] [color-adjust:exact]">
          
          {/* Header Title */}
          <div className="border-b-2 border-gray-200 pb-4 mb-8">
            <h1 className="text-3xl font-extrabold tracking-tight">
              {reportData.type} Report
            </h1>
          </div>

          {/* Report Information Section */}
          <div className="mb-8">
            <h3 className="text-sm font-bold mb-3">Report Information</h3>
            <div className="grid grid-cols-2 gap-y-3 gap-x-12 bg-gray-50 p-5 border border-gray-200 text-xs">
              <div className="flex justify-between">
                <span className="text-gray-500">Report ID</span>
                <span className="font-mono font-medium">2025-ORD-AGG-0014</span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-500">Report Type</span>
                <span className="font-medium">{reportData.type}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-500">Generated By</span>
                <span className="font-medium">{reportData.generatedBy}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-500">Date Generated</span>
                <span className="font-medium">{reportData.dateGenerated}</span>
              </div>
              <div className="flex justify-between col-span-2">
                <span className="text-gray-500">Reporting Period</span>
                <span className="font-medium">December 1, 2025 – December 7, 2025</span>
              </div>
            </div>
          </div>

          {/* Data Scope Section */}
          <div className="mb-10">
            <h3 className="text-sm font-bold mb-3">Data Scope</h3>
            <div className="bg-gray-50 border border-gray-200 p-5 text-xs text-gray-700">
              <ul className="list-disc pl-4 space-y-1">
                <li>Orders recorded within the reporting period</li>
                <li>Aggregated by item and supplier</li>
                <li>Cancelled and draft orders excluded</li>
              </ul>
            </div>
          </div>

          {/* Table 1: Item Order Totals */}
          <div className="mb-10 break-inside-avoid">
            <h3 className="text-sm font-bold mb-3">Item Order Totals</h3>
            <table className="w-full text-xs border border-gray-200 border-collapse">
              <thead>
                <tr className="bg-black text-white">
                  <th className="py-2 px-4 text-left font-bold">Product Code</th>
                  <th className="py-2 px-4 text-left font-bold">Item Name</th>
                  <th className="py-2 px-4 text-center font-bold">Total Quantity</th>
                  <th className="py-2 px-4 text-right font-bold">Unit</th>
                </tr>
              </thead>
              <tbody>
                <tr className="border-b border-gray-200">
                  <td className="py-2 px-4 font-mono text-gray-600">PNL-101</td>
                  <td className="py-2 px-4 font-medium">3/4&quot; Marine Plywood 4x8</td>
                  <td className="py-2 px-4 text-center font-bold">320</td>
                  <td className="py-2 px-4 text-right">Sheet</td>
                </tr>
                <tr className="border-b border-gray-200 bg-gray-50">
                  <td className="py-2 px-4 font-mono text-gray-600">HW-201</td>
                  <td className="py-2 px-4 font-medium">Soft-Close Cabinet Hinge (Pair)</td>
                  <td className="py-2 px-4 text-center font-bold">980</td>
                  <td className="py-2 px-4 text-right">Pair</td>
                </tr>
              </tbody>
            </table>
          </div>

          {/* Page Break - Forces the next section to a new page if needed */}
          <div className="break-before-page"></div>

          {/* Table 2: Supplier Breakdown */}
          <div className="mb-10 break-inside-avoid mt-8 print:mt-0">
            <h3 className="text-sm font-bold mb-3">Supplier Order Breakdown</h3>
            <table className="w-full text-xs border border-gray-200 border-collapse">
              <thead>
                <tr className="bg-black text-white">
                  <th className="py-2 px-4 text-left font-bold">Supplier</th>
                  <th className="py-2 px-4 text-left font-bold">Product Code</th>
                  <th className="py-2 px-4 text-center font-bold">Quantity</th>
                </tr>
              </thead>
              <tbody>
                <tr className="border-b border-gray-200">
                  <td className="py-2 px-4 font-medium">BuildPro Supplies</td>
                  <td className="py-2 px-4 font-mono text-gray-600">PNL-101</td>
                  <td className="py-2 px-4 text-center font-bold">320</td>
                </tr>
                <tr className="border-b border-gray-200 bg-gray-50">
                  <td className="py-2 px-4 font-medium">Hardware Solutions Inc.</td>
                  <td className="py-2 px-4 font-mono text-gray-600">HW-201</td>
                  <td className="py-2 px-4 text-center font-bold">980</td>
                </tr>
              </tbody>
            </table>
          </div>

          {/* End of Document Footer */}
          <div className="mt-12 text-center text-[10px] text-gray-400 font-bold uppercase tracking-widest border-t border-gray-200 pt-4 break-inside-avoid">
            — End of {reportData.type} Data —
          </div>

        </div>
      </div>
    );
  }
);
PrintableReport.displayName = "PrintableReport";