"use client";

import { ChevronLeft, ChevronRight } from "lucide-react";
import { Dialog, DialogContent, DialogTitle } from "@/components/ui/dialog"; // Added DialogTitle here!
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { ScrollArea } from "@/components/ui/scroll-area";
import { ReportRecord } from "./reports-history-table";

interface ReportViewerModalProps {
  isOpen: boolean;
  onClose: () => void;
  reportData: ReportRecord | null;
}

export const ReportViewerModal = ({ isOpen, onClose, reportData }: ReportViewerModalProps) => {
  if (!reportData) return null;

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="sm:max-w-[850px] p-0 overflow-hidden border-none shadow-2xl bg-white rounded-2xl">
        
        <ScrollArea className="max-h-[85vh]">
          <div className="p-12 space-y-10">
            
            {/* Header Document Title - Changed to DialogTitle to fix the Radix UI accessibility error! */}
            <div className="border-b border-gray-200 pb-6">
              <DialogTitle className="text-3xl font-extrabold text-gray-900 tracking-tight">
                {reportData.type} Report
              </DialogTitle>
            </div>

            {/* Metadata Blocks */}
            <div className="space-y-8">
              {/* Report Information */}
              <div className="space-y-3">
                <h3 className="text-sm font-semibold text-gray-800">Report Information</h3>
                <div className="grid grid-cols-2 gap-y-4 gap-x-12 bg-gray-50/50 border border-gray-100 p-6 rounded-xl">
                  <div className="flex justify-between items-center text-sm">
                    <span className="text-gray-500">Report ID</span>
                    <span className="font-medium text-gray-900 font-mono text-xs">2025-ORD-AGG-0014</span>
                  </div>
                  <div className="flex justify-between items-center text-sm">
                    <span className="text-gray-500">Report Type</span>
                    <span className="font-medium text-gray-900">{reportData.type}</span>
                  </div>
                  <div className="flex justify-between items-center text-sm">
                    <span className="text-gray-500">Generated By</span>
                    <span className="font-medium text-gray-900">{reportData.generatedBy}</span>
                  </div>
                  <div className="flex justify-between items-center text-sm">
                    <span className="text-gray-500">Date Generated</span>
                    <span className="font-medium text-gray-900">{reportData.dateGenerated}</span>
                  </div>
                  <div className="flex justify-between items-center text-sm col-span-2">
                    <span className="text-gray-500">Reporting Period</span>
                    <span className="font-medium text-gray-900">December 1, 2025 – December 7, 2025</span>
                  </div>
                </div>
              </div>

              {/* Data Scope */}
              <div className="space-y-3">
                <h3 className="text-sm font-semibold text-gray-800">Data Scope</h3>
                <div className="bg-gray-50/50 border border-gray-100 p-6 rounded-xl text-sm text-gray-700 space-y-2">
                  <ul className="list-disc pl-5 space-y-1">
                    <li>Orders recorded within the reporting period</li>
                    <li>Aggregated by item and supplier</li>
                    <li>Cancelled and draft orders excluded</li>
                  </ul>
                </div>
              </div>
            </div>

            {/* Formal Data Tables */}
            <div className="space-y-6 pt-4">
              <h3 className="text-sm font-semibold text-gray-800">Item Order Totals</h3>
              <div className="border border-gray-200 rounded-lg overflow-hidden">
                <Table className="text-xs">
                  {/* Formal Black Header */}
                  <TableHeader className="bg-black">
                    <TableRow className="hover:bg-black border-none">
                      <TableHead className="text-white font-bold h-10 px-6">Product Code</TableHead>
                      <TableHead className="text-white font-bold h-10 px-6">Item Name</TableHead>
                      <TableHead className="text-white font-bold h-10 px-6 text-center">Total Quantity</TableHead>
                      <TableHead className="text-white font-bold h-10 px-6 text-right">Unit</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    <TableRow className="border-b border-gray-100 hover:bg-gray-50/50">
                      <TableCell className="px-6 py-3 font-mono text-gray-500">PNL-101</TableCell>
                      <TableCell className="px-6 py-3 font-medium text-gray-800">3/4&quot; Marine Plywood 4x8</TableCell>
                      <TableCell className="px-6 py-3 text-center font-bold text-gray-900">320</TableCell>
                      <TableCell className="px-6 py-3 text-right text-gray-600">Sheet</TableCell>
                    </TableRow>
                    <TableRow className="border-none hover:bg-gray-50/50">
                      <TableCell className="px-6 py-3 font-mono text-gray-500">HW-201</TableCell>
                      <TableCell className="px-6 py-3 font-medium text-gray-800">Soft-Close Cabinet Hinge (Pair)</TableCell>
                      <TableCell className="px-6 py-3 text-center font-bold text-gray-900">980</TableCell>
                      <TableCell className="px-6 py-3 text-right text-gray-600">Pair</TableCell>
                    </TableRow>
                  </TableBody>
                </Table>
              </div>
            </div>

            {/* End of Document Footer & Pagination */}
            <div className="pt-12 pb-4 space-y-8">
              <div className="flex items-center justify-center gap-4">
                <div className="h-px bg-gray-200 w-12"></div>
                <span className="text-[10px] uppercase tracking-widest text-gray-400 font-bold">End of Order Aggregate Data</span>
                <div className="h-px bg-gray-200 w-12"></div>
              </div>
              
              <div className="flex justify-center items-center gap-4">
                <button className="h-8 w-8 rounded-full border border-gray-300 flex items-center justify-center text-gray-600 hover:bg-gray-50 transition-colors">
                  <ChevronLeft className="w-4 h-4" />
                </button>
                <span className="text-sm font-bold text-gray-700">Page 1 of 2</span>
                <button className="h-8 w-8 rounded-full border border-gray-300 flex items-center justify-center text-gray-600 hover:bg-gray-50 transition-colors">
                  <ChevronRight className="w-4 h-4" />
                </button>
              </div>
            </div>

          </div>
        </ScrollArea>
      </DialogContent>
    </Dialog>
  );
};