"use client";

import { useState } from "react";
import { Download, Eye, Trash2 } from "lucide-react";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Button } from "@/components/ui/button";

export interface ReportRecord {
  id: string;
  type: string;
  dateGenerated: string;
  generatedBy: string;
}

interface ReportsHistoryTableProps {
  data: ReportRecord[];
  onView: (report: ReportRecord) => void;
  onDelete: (id: string) => void;
  onDownload: (report: ReportRecord) => void;
}

export const ReportsHistoryTable = ({ data = [], onView, onDelete, onDownload }: ReportsHistoryTableProps) => {
  const [currentPage, setCurrentPage] = useState(1);
  const itemsPerPage = 5;
  
  if (!data || data.length === 0) {
    return (
      <div className="p-8 text-center text-gray-500 border rounded-2xl border-dashed mt-4 bg-gray-50/30">
        No reports found matching your criteria.
      </div>
    );
  }

  const indexOfLastItem = currentPage * itemsPerPage;
  const indexOfFirstItem = indexOfLastItem - itemsPerPage;
  const currentItems = data.slice(indexOfFirstItem, indexOfLastItem);
  const totalPages = Math.ceil(data.length / itemsPerPage);

  return (
    <div className="space-y-4">
      <div className="rounded-2xl border border-gray-100 overflow-hidden">
        <Table className="text-sm border-collapse">
          <TableHeader>
            <TableRow className="hover:bg-transparent border-b border-gray-100 bg-gray-50/50">
              <TableHead className="text-[11px] uppercase tracking-widest px-6 py-4 text-gray-500 font-bold">Report Type</TableHead>
              <TableHead className="text-[11px] uppercase tracking-widest px-6 py-4 text-gray-500 font-bold text-center">Date Generated</TableHead>
              <TableHead className="text-[11px] uppercase tracking-widest px-6 py-4 text-gray-500 font-bold text-center">Generated By</TableHead>
              <TableHead className="text-[11px] uppercase tracking-widest px-6 py-4 text-gray-500 font-bold text-right">Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody className="divide-y divide-gray-50">
            {currentItems.map((report) => (
              <TableRow key={report.id} className="group transition-colors hover:bg-black cursor-default border-none">
                <TableCell className="px-6 py-5 font-medium text-gray-800 group-hover:text-white">{report.type}</TableCell>
                <TableCell className="px-6 py-5 text-center font-mono text-xs text-gray-500 group-hover:text-zinc-400">{report.dateGenerated}</TableCell>
                <TableCell className="px-6 py-5 text-center text-gray-600 group-hover:text-zinc-300">{report.generatedBy}</TableCell>
                <TableCell className="px-6 py-5 text-right">
                  <div className="flex items-center justify-end gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                    <Button variant="ghost" size="icon" className="h-8 w-8 text-zinc-400 hover:text-white hover:bg-white/10" onClick={() => onView(report)}>
                      <Eye className="w-4 h-4" />
                    </Button>
                    <Button variant="ghost" size="icon" className="h-8 w-8 text-zinc-400 hover:text-white hover:bg-white/10" onClick={() => onDownload(report)}>
                      <Download className="w-4 h-4" />
                    </Button>
                    <Button variant="ghost" size="icon" className="h-8 w-8 text-zinc-400 hover:text-red-400 hover:bg-red-500/10" onClick={() => onDelete(report.id)}>
                      <Trash2 className="w-4 h-4" />
                    </Button>
                  </div>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>

      <div className="p-6 border border-gray-100 rounded-2xl flex items-center justify-between text-[11px] text-gray-400 uppercase tracking-tighter bg-white">
        <span>Showing {indexOfFirstItem + 1} to {Math.min(indexOfLastItem, data.length)} of {data.length} results</span>
        <div className="flex items-center gap-1">
          <Button variant="outline" className="h-8 px-3 text-[11px] border-gray-200 hover:bg-gray-50 disabled:opacity-30" onClick={() => setCurrentPage(p => Math.max(1, p - 1))} disabled={currentPage === 1}>Previous</Button>
          {[...Array(totalPages)].map((_, i) => (
            <Button key={i} variant={currentPage === i + 1 ? "default" : "outline"} onClick={() => setCurrentPage(i + 1)} className={`h-8 w-8 p-0 text-[11px] ${currentPage === i + 1 ? "bg-black text-white hover:bg-zinc-800" : "border-gray-200 hover:bg-gray-50 text-gray-600"}`}>{i + 1}</Button>
          ))}
          <Button variant="outline" className="h-8 px-3 text-[11px] border-gray-200 hover:bg-gray-50 disabled:opacity-30" onClick={() => setCurrentPage(p => Math.min(totalPages, p + 1))} disabled={currentPage === totalPages || totalPages === 0}>Next</Button>
        </div>
      </div>
    </div>
  );
};