"use client";

import { Download, Eye, Trash2 } from "lucide-react";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Button } from "@/components/ui/button";

export interface Report {
  reportId: number;
  reportType: string;
  dateCreated: Date ;
  username: string;
  dateStart: Date;
  dateEnd: Date;
}

const formatDate = (date: Date | string | null) => {
    if (!date) return '-';
    return new Date(date).toISOString().replace('T', ' ').slice(0, 16)
   
  };

export const ReportsHistoryTable = ({ data, onView, onDelete, onDownload }: any) => {
  return (
    <div className="rounded-2xl border border-gray-100 overflow-hidden">
      <Table>
        <TableHeader className="bg-gray-50">
          <TableRow>
            <TableHead className="px-6 py-4 font-bold text-[10px] uppercase text-gray-400">Type</TableHead>
            <TableHead className="text-center font-bold text-[10px] uppercase text-gray-400">Date</TableHead>
            <TableHead className="text-center font-bold text-[10px] uppercase text-gray-400">Generated By</TableHead>
            <TableHead className="text-center font-bold text-[10px] uppercase text-gray-400">Date Start</TableHead>
            <TableHead className="text-center font-bold text-[10px] uppercase text-gray-400">Date End</TableHead>
            <TableHead className="text-right px-6 font-bold text-[10px] uppercase text-gray-400">Actions</TableHead>

          </TableRow>
        </TableHeader>
        <TableBody>
          {data.map((report: any) => (
            <TableRow key={report.reportId} className="group hover:bg-black transition-colors">
              <TableCell className="px-6 py-4 font-bold group-hover:text-white">{report.reportType}</TableCell>
            
              <TableCell className="text-center text-gray-500 group-hover:text-gray-400 font-mono text-xs">{formatDate(report.dateCreated)}</TableCell>
              <TableCell className="text-center text-gray-500 group-hover:text-gray-400 font-mono text-xs">{(report.username)}</TableCell>
              <TableCell className="text-center text-gray-500 group-hover:text-gray-400 font-mono text-xs">{formatDate(report.dateStart)}</TableCell>
              <TableCell className="text-center text-gray-500 group-hover:text-gray-400 font-mono text-xs">{formatDate(report.dateEnd)}</TableCell>
              <TableCell className="px-6 text-right">
                <div className="flex justify-end gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                  <Button variant="ghost" size="icon" onClick={() => onView(report)} className="text-white hover:bg-white/20"><Eye className="w-4 h-4" /></Button>
                  <Button variant="ghost" size="icon" onClick={() => onDownload(report)} className="text-white hover:bg-white/20"><Download className="w-4 h-4" /></Button>
                  <Button variant="ghost" size="icon" onClick={() => onDelete(report.reportId)} className="text-red-400 hover:bg-red-500/20"><Trash2 className="w-4 h-4" /></Button>
                </div>
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </div>
  );
};