"use client";

import { Download, Eye, Trash2 } from "lucide-react";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Button } from "@/components/ui/button";

export interface Report {
  reportId: number;
  reportType: string;
  dateCreated: Date ;
  username?: string;
  dateStart: Date;
  dateEnd: Date;
}

const formatDate = (date: Date | string | null) => {
    if (!date) return '-';
    return new Date(date).toLocaleString()
  };

export const ReportsHistoryTable = ({ data, onView, onDelete, onDownload }: any) => {
  return (
    <div className="rounded-2xl border border-gray-100 overflow-hidden">
      <Table className="text-sm border-collapse w-full">
        <TableHeader className="bg-gray-50/50">
          <TableRow>
            <TableHead className="px-6 py-4 font-bold text-[10px] uppercase text-gray-400 text-left">Type</TableHead>
            <TableHead className="px-6 py-4 font-bold text-[10px] uppercase text-gray-400 text-center">Date</TableHead>
            <TableHead className="px-6 py-4 font-bold text-[10px] uppercase text-gray-400 text-center">Generated By</TableHead>
            <TableHead className="px-6 py-4 font-bold text-[10px] uppercase text-gray-400 text-center">Date Start</TableHead>
            <TableHead className="px-6 py-4 font-bold text-[10px] uppercase text-gray-400 text-center">Date End</TableHead>
            <TableHead className="px-6 py-4 font-bold text-[10px] uppercase text-gray-400 text-right">Actions</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {data.map((report: any) => (
            <TableRow key={report.reportId} className="group hover:bg-[#0f172a] transition-colors border-b border-gray-100 last:border-0">
              
              <TableCell className="px-6 py-4 font-bold text-gray-900 group-hover:text-white transition-colors text-left">
                {report.reportType}
              </TableCell>
            
              <TableCell className="px-6 py-4 text-center text-gray-500 group-hover:text-white transition-colors font-mono text-xs">
                {formatDate(report.dateCreated)}
              </TableCell>
              
              <TableCell className="px-6 py-4 text-center text-gray-500 group-hover:text-white transition-colors font-mono text-xs">
                {report.username}
              </TableCell>
              
              <TableCell className="px-6 py-4 text-center text-gray-500 group-hover:text-white transition-colors font-mono text-xs">
                {formatDate(report.dateStart)}
              </TableCell>
              
              <TableCell className="px-6 py-4 text-center text-gray-500 group-hover:text-white transition-colors font-mono text-xs">
                {formatDate(report.dateEnd)}
              </TableCell>
              
              <TableCell className="px-6 py-4 text-right">
                {/* Removed opacity classes so buttons are always visible */}
                <div className="flex justify-end gap-2 group-hover:text-white transition-colors">
                  <Button variant="ghost" size="icon" onClick={() => onView(report)} className="text-slate-400 group-hover:text-white hover:bg-slate-800 hover:text-white transition-colors" title="View">
                    <Eye className="w-4 h-4" />
                  </Button>
                  <Button variant="ghost" size="icon" onClick={() => onDownload(report)} className="text-slate-400 group-hover:text-white hover:bg-slate-800 hover:text-white transition-colors" title="Download">
                    <Download className="w-4 h-4" />
                  </Button>
                  <Button variant="ghost" size="icon" onClick={() => onDelete(report)} className="text-slate-400 group-hover:text-white hover:!text-red-400 hover:bg-slate-800 transition-colors" title="Delete">
                    <Trash2 className="w-4 h-4" />
                  </Button>
                </div>
              </TableCell>

            </TableRow>
          ))}
        </TableBody>
      </Table>
    </div>
  );
};