"use client";

import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Report } from "./reports-history-table";

// Aligned MOCK data
const MOCK_DATA = {
  suppliers: [
    { name: "BuildPro Supplies", committed: 150000, disbursed: 125000, pending: "3/4 Marine Plywood (50)", status: "awaiting delivery" },
    { name: "Hardware Sol.", committed: 45000, disbursed: 45000, pending: "None", status: "delivered" },
    { name: "Steel Corp", committed: 80000, disbursed: 0, pending: "12mm Deformed Bars", status: "awaiting payment" },
  ],
  inventory: [
    { item: "3/4 Marine Plywood", start: 500, end: 420 },
    { item: "1/2 Marine Plywood", start: 200, end: 195 },
  ]
};

export const ReportViewerModal = ({ isOpen, onClose, reportData }: { isOpen: boolean; onClose: () => void; reportData: Report | null }) => {
  if (!reportData) return null;

  const getStatusStyle = (status: string) => {
    const map: Record<string, string> = {
      "delivered": "bg-green-100 text-green-700 border-green-200",
      "awaiting delivery": "bg-blue-100 text-blue-700 border-blue-200",
      "incomplete delivery": "bg-red-100 text-red-700 border-red-200",
      "awaiting payment": "bg-purple-100 text-purple-700 border-purple-200",
      "approved": "bg-cyan-100 text-cyan-700 border-cyan-200",
    };
    return map[status] || "bg-gray-100 text-gray-700";
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="sm:max-w-[950px] p-0 overflow-hidden border-none shadow-2xl rounded-3xl">
        {/* Header - Aligned to your NewItemModal style */}
        <DialogHeader className="px-8 py-8 border-b border-gray-100 flex justify-center items-center">
          <DialogTitle className="text-2xl font-medium text-gray-900 tracking-tight">
            Month-End Summary Details
          </DialogTitle>
        </DialogHeader>

        {/* Content Area - Using the p-8 space-y-5 pattern */}
        <div className="p-8 space-y-8 max-h-[70vh] overflow-y-auto bg-white">
          
          {/* Metadata Grid */}
          <div className="grid grid-cols-2 gap-6 bg-gray-50/50 border border-gray-100 p-6 rounded-2xl text-sm">
            <div className="flex justify-between items-center">
              <span className="text-gray-500 font-semibold uppercase text-[10px] tracking-widest">Generated By</span>
              <span className="font-bold text-gray-900">{reportData.username}</span>
            </div>
            <div className="flex justify-between items-center">
              <span className="text-gray-500 font-semibold uppercase text-[10px] tracking-widest">Report Date</span>
              <span className="font-bold text-gray-900">{reportData.dateCreated?.toLocaleDateString()}</span>
            </div>
          </div>

          {/* Supplier Audit Table */}
          <div className="space-y-4">
            <h3 className="text-xs font-bold uppercase tracking-widest text-gray-400 ml-1">Supplier Transaction Audit</h3>
            <div className="border border-gray-100 rounded-2xl overflow-hidden shadow-sm">
              <Table>
                <TableHeader className="bg-black">
                  <TableRow className="hover:bg-black">
                    <TableHead className="text-white font-bold h-12 px-6">Supplier</TableHead>
                    <TableHead className="text-white font-bold h-12 text-right">Total Committed</TableHead>
                    <TableHead className="text-white font-bold h-12 text-right">Disbursed Amount</TableHead>
                    <TableHead className="text-white px-6 font-bold">Pending Materials</TableHead>
                    <TableHead className="text-white text-right px-6 font-bold">Status</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {MOCK_DATA.suppliers.map((s, i) => (
                    <TableRow key={i} className="border-b border-gray-50 hover:bg-gray-50/50">
                      <TableCell className="px-6 py-5 font-bold">{s.name}</TableCell>
                      <TableCell className="text-right py-5 text-gray-500 font-mono">₱{s.committed.toLocaleString()}</TableCell>
                      <TableCell className="text-right py-5 font-bold text-green-600 font-mono">₱{s.disbursed.toLocaleString()}</TableCell>
                      <TableCell className="px-6 py-5 text-xs italic text-gray-500">{s.pending}</TableCell>
                      <TableCell className="text-right px-6 py-5">
                        <Badge variant="outline" className={`uppercase text-[9px] font-black tracking-tighter ${getStatusStyle(s.status)}`}>
                          {s.status}
                        </Badge>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          </div>

          {/* Stock Movement */}
          <div className="space-y-4">
            <h3 className="text-xs font-bold uppercase tracking-widest text-gray-400 ml-1">Stock Movement Analysis</h3>
            <div className="grid grid-cols-2 gap-4">
              {MOCK_DATA.inventory.map((item, i) => (
                <div key={i} className="p-6 bg-gray-50/50 border border-gray-100 rounded-2xl flex justify-between items-center">
                  <span className="font-bold text-sm text-gray-800">{item.item}</span>
                  <div className="flex gap-4">
                    <div className="text-center border-r pr-4 border-gray-100">
                      <p className="text-[9px] font-black text-gray-400 uppercase tracking-widest">Opening</p>
                      <p className="font-mono font-bold text-gray-900">{item.start}</p>
                    </div>
                    <div className="text-center">
                      <p className="text-[9px] font-black text-red-400 uppercase tracking-widest">Closing</p>
                      <p className="font-mono font-bold text-red-600">{item.end}</p>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Footer - Aligned to your NewItemModal style */}
        <DialogFooter className="px-8 py-6 bg-gray-50/50 border-t border-gray-100 flex flex-row justify-end gap-3">
          <Button variant="outline" onClick={onClose} className="px-8 h-11 rounded-xl font-bold text-gray-500 hover:text-gray-900">
            Close
          </Button>
          <Button className="bg-[#0f172a] text-white px-10 h-11 rounded-xl font-bold shadow-lg shadow-black/10 hover:bg-[#0f172a]/70">
            Download PDF
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};